name: Build and Push Vote Docker Image

on:
  push:
    paths:
      - 'vote/**'
      - '.github/workflows/vote-cicd.yml'
  pull_request:
    paths:
      - 'vote/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate incremental image tag
        id: set-tag
        run: echo "tag=build-${{ github.run_number }}" >> "$GITHUB_OUTPUT"

      - name: Azure Login via OIDC
        uses: azure/login@v1.6.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
      #    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}

  #    - name: Log in to ACR
  #      uses: azure/docker-login@v1
  #      with:
  #        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
  #        username: ${{ secrets.AZURE_CLIENT_ID }}
  #        password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/vote-app-image:${{ steps.set-tag.outputs.tag }} ./vote
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/vote-app-image:${{ steps.set-tag.outputs.tag }}

      - name: Optionally tag latest
        run: |
          docker tag ${{ secrets.ACR_LOGIN_SERVER }}/vote-app-image:${{ steps.set-tag.outputs.tag }} ${{ secrets.ACR_LOGIN_SERVER }}/vote-app-image:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/vote-app-image:latest