name: Build Vote Docker Image

on:
  push:
    paths:
      - 'vote/**'
      - '.github/workflows/vote-cicd.yml'
  pull_request:
    paths:
      - 'vote/**'

permissions:
  id-token: write  # Required for OIDC login
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate incremental image tag
        id: set-tag
        run: |
          echo "tag=build-${{ github.run_number }}" >> "$GITHUB_OUTPUT"

      - name: Log in to DockerHub (optional)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t vote-app-image:${{ steps.set-tag.outputs.tag }} ./vote

      - name: Set output tag
        id: tag-output
        run: echo "tag=${{ steps.set-tag.outputs.tag }}" >> "$GITHUB_OUTPUT"

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login via OIDC
        uses: azure/login@v1.6.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
          #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Debug tag
          run: echo "Pushing tag: ${{ steps.set-tag.outputs.tag }}"

      - name: Optionally tag latest
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/vote-app-image:${{ steps.set-tag.outputs.tag }}