name: Build and Push Vote Docker Image

on:
  push:
    paths:
      - 'vote/**'
      - '.github/workflows/vote-cicd.yml'
  pull_request:
    paths:
      - 'vote/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate incremental image tag
        id: set-tag
        run: echo "tag=build-${{ github.run_number }}" >> "$GITHUB_OUTPUT"

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/vote-app-image:${{ steps.set-tag.outputs.tag }}
          file: vote/Dockerfile