name: Build Vote Docker Image

on:
  push:
    paths:
      - 'vote/**'
      - '.github/workflows/vote-cicd.yml'
  pull_request:
    paths:
      - 'vote/**'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub (optional)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t vote-app-image ./vote
          docker save vote-app-image > vote-app-image.tar
      
      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: vote-app-image
          path: vote-app-image.tar

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download built image
        uses: actions/download-artifact@v2
        with:
          name: vote-app-image
          path: .

      - name: Load Docker image
        run: docker load < vote-app-image.tar

      - name: Log in to Azure
        uses: azure/login@v1.6.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL
          

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
          

      - name: Tag and push to ACR
        run: |
          docker tag vote-app-image ${{ secrets.ACR_LOGIN_SERVER }}/vote-app-image:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/vote-app-image:latest
